### ISSUE TITLE
`plusTime` with year and months

### ISSUE THREAD

**Issue by vanlooverenkoen** [ehn-dcc-development/dgc-business-rules#105]
We need to validate that a date is 18 years + 3months ago. 
As far as I can see you can not do that with `plusTime` or am I missing something?

**Comment by vanlooverenkoen** [comment]
Never mind, it is to early for me to think 😂 
we will just 219 months

**Comment by dslmeinte** [comment]
Hi @vanlooverenkoen , You're right: you can use only one time unit per `plusTime` operation, and you can't compose `plusTime` operations. I don't mind not having to extend CertLogic, provided adding 219 months works for your use case :)

I'm curious: is your use case DCC-related?

**Comment by vanlooverenkoen** [comment]
Yes indeed
