### ISSUE TITLE
SWIFT : Truthy for Array/Strings and Dictionaries

### ISSUE THREAD

**Issue by SchulzeStTSI** [ehn-dcc-development/dgc-business-rules#16]
Currently the truthiness of string, arrays and dictionaries in the swift lib are bound to the content as you see here: 

case let .String(string):
            return !string.isEmpty
        case let .Array(array):
            return !array.isEmpty
        case .Dictionary(dictionary):
            return !dictionary!.isEmpty

In the case of empty/null its false. What is the correct behavior? Should it be false across all implementations only in the case of null, or in the case of null and empty, or in case of empty truthy? 

E.g. for "!": [] or "!":{}

**Comment by dslmeinte** [comment]
Agree that an empty array should be falsy: see Pull Request #18 
Let's discuss about truthiness of “empty” objects `{}`.
