### ISSUE TITLE
Empty/Too much Expressions

### ISSUE THREAD

**Issue by SchulzeStTSI** [ehn-dcc-development/dgc-business-rules#17]
What is the correct output for "if":[]? I would assume false, but some interpretations say null. Same for {"if":[false, "apple", false, "banana", false, "carrot"]} (too much expressions)

**Comment by dslmeinte** [comment]
Both cases I'd deem to be undefined behaviour. The “2*n + 1”-operands use of `if` exists in JsonLogic, but I wouldn't be happy to overload `if` with `when/switch` functionality.

**Comment by SchulzeStTSI** [comment]
Shall we keep it on nil/null then?

**Comment by dslmeinte** [comment]
Returning `nil`/`null` would make it **defined** behaviour.

To be sure: you mean: what's the evaluation result of an `if` where the guard (the 1st argument) evaluates to the empty array `[]`?

**Comment by SchulzeStTSI** [comment]
Yes. I mean "if": [] and "all":[], "some":[] All kind of empty expressions return currently null/nil.

**Comment by dslmeinte** [comment]
An `if` on a non-truthy/falsy guard should be undefined behaviour, to avoid weird corner cases.
`all` and `some` are not in CertLogic, but can be implemented using a `reduce`. A `reduce` on an empty main operand evaluates to the `initial` operand.

**Comment by dslmeinte** [comment]
@SchulzeStTSI Is this enough of an answer? / Can I close the issue?

**Comment by SchulzeStTSI** [comment]
@dslmeinte Yes we can close it. JSON Logic Swift passes all CertLogic Unittests now.
