### ISSUE TITLE
test-runner.ts does not find module ...

### ISSUE THREAD

**Issue by chris-baumann-at** [ehn-dcc-development/dgc-business-rules#20]
When running "dgc-business-rules\rules-runner\javascript\rules-runner-js>npm run build"

src/test-runner.ts:4:26 - error TS2307: Cannot find module '../../../../certlogic/certlogic-validation' or its corresponding type declarations.

import { validate } from "../../../../certlogic/certlogic-validation"

**Comment by dslmeinte** [comment]
I'm not able to reproduce this, but I'll clean up the `package.json` so it should be less of a problem.

**Comment by dslmeinte** [comment]
@chris-baumann-at Can you try https://github.com/ehn-dcc-development/dgc-business-rules/pull/21 to see whether that fixes your problem?

**Comment by dslmeinte** [comment]
Closing due to no response. Feel free to open at your discretion.
