### ISSUE TITLE
Binary Operators with object

### ISSUE THREAD

**Issue by SchulzeStTSI** [ehn-dcc-development/dgc-business-rules#24]
In the test cases is one example for and which should be clarified: 

{
          "data": [
            true,
            {}
          ],
          "expected": {}
        }

It's used in an and condition. If {} is resolved to false, should the expected then not be false instead of {}?

**Comment by dslmeinte** [comment]
This is compliant to what JsonLogic does, at least according to the documentation and the original JS implementation. The first falsy value is returned (which is `{}`), or the last element in the operand list.

**Comment by SchulzeStTSI** [comment]
Okay, thank you:) I can close this issue.
