### ISSUE TITLE
VR-EU-0001

### ISSUE THREAD

**Issue by kruzikh** [ehn-dcc-development/dgc-business-rules#26]
All entries of the vaccine-medicinal-product value set are valid (if "active"=true). Not only those approved by EMA! 
Value set is being maintained by semantic subgroup and might include also vaccines that are not approved by EMA if decided by the M/S. 

So, this rule is not correct according to my opinion.
 
"id": "VR-EU-0001",
    "businessDescription": "EMA must approve allowed vaccines.",
    "description": "Only vaccines in the allowed valueset that have been approved by the EMA are allowed.",

**Comment by dslmeinte** [comment]
I don't think that the `active` flag can be accorded the semantics of “is a vaccine approved by the EMA”. That's also [why the implementation of the rule](https://github.com/eu-digital-green-certificates/dgc-business-rules-testdata/blob/main/EU/VR-EU-0001/rule.json#L33) mentions the approved vaccines explicitly.

But that's an implementation choice (made by me), so it'd be good thing if we could agree on a way to add the information of whether a value in a value set is (at that moment!) an EMA-approved “thing” - could also apply to RAT manufacturer.

**Comment by kruzikh** [comment]
I really thing that these are two different things.
Active/inactive concepts is one problem, which is described in #25 
Business rule that is checking if the vaccine has been approved by EMA is another. After another round of reading of the regulation, I must take back my comment. You are right in that M/S SHELL accept only products with EMA marketing authorization and MAY accept also other products (article 5, paragraph 5). So the proposed business rule is correct.

**Comment by dslmeinte** [comment]
OK, closing this issue.
