### ISSUE TITLE
DateTime parsing should parse DateTimes without timezone

### ISSUE THREAD

**Issue by ubamrein** [ehn-dcc-development/dgc-business-rules#31]
In this file https://github.com/ehn-dcc-development/dgc-business-rules/blob/88a6e3bae58b8ff7cede2677982ee4fa771ee405/certlogic/certlogic-kotlin/src/main/kotlin/eu/ehn/dcc/certlogic/JsonDateTime.java#L37 the datetime parsing was adjusted to be more relaxed. Nevertheless, some certificates contain timestamps without timezone information (e.g. [this one](https://github.com/eu-digital-green-certificates/dcc-quality-assurance/blob/main/BG/1.0.0/specialcases/VAC-NULL-DATETIME.png)). This means that the parsing of the datetime would fail, as the regular expression does not match a datetime string without timezone information and hence https://github.com/ehn-dcc-development/dgc-business-rules/blob/9a5b2aebc968a99041d9de658445d1e1263f35f4/certlogic/certlogic-kotlin/src/main/kotlin/eu/ehn/dcc/certlogic/JsonDateTime.java#L45 can never be null. 

> To adjust for that the capture group 8 would need to be optional. 

Further, reading enumerated capturing groups seems rather erroneous, so I would propose the following regular expression:

```
^(?<year>\d{4})-(?<month>\d{2})-(?<day>\d{2})T(?<time_hour>\d{2}):(?<time_minute>\d{2}):(?<time_second>\d{2})(?<fractional>\.\d+?)?(?<timezone>Z|(?<offset_hour>[+-]\d{2}):?(?<offset_minute>\d{2})?)?$
```

If not already known, I recommend [regex101](https://regex101.com/) for testing purposes, as it allows for easy testing and debugging of regular expressions.

**Comment by dslmeinte** [comment]
These are two separate issues:

1. Deal with date(-times) without timezone info.
2. Use named capturing groups.

Can you make a second issue for item 2? It's a purely technical concern, not a functional one like item 1. (I'm familiar with regex101: it's a good one, indeed ;))

For item 1: what does a date(-time) without timezone info _mean_ exactly? There's a good reason the [DCC JSON specification](https://ec.europa.eu/health/sites/default/files/ehealth/docs/covid-certificate_json_specification_en.pdf) prescribes a date-time format including timezone info: there's quite some variance in timezones even within the EU (let alone when taking overseas territories into account), and with validity windows a couple of days in length a couple of hours potential difference start to matter.

(Also: Postel's Law says to be lenient in acceptance, and strict in issuance, but I'm wondering what else we're going to have to accommodate for.)

**Comment by ubamrein** [comment]
> These are two separate issues:

Fair enough, I will make another issue tomorrow :) 

> For item 1: what does a date(-time) without timezone info _mean_ exactly? There's a good reason the [DCC JSON specification](https://ec.europa.eu/health/sites/default/files/ehealth/docs/covid-certificate_json_specification_en.pdf) prescribes a date-time format including timezone info: there's quite some variance in timezones even within the EU (let alone when taking overseas territories into account), and with validity windows a couple of days in length a couple of hours potential difference start to matter.

Well, I am totally the same opinion. The problem is, there are already certificates issued that have timestamps without a timezone. The ISO allows date-time strings without timezones and mentions to use the `local timezone`. Since this is unpractical, we are just assuming a UTC-Offset (+00:00). 

I'm just raising this issue, since we were told to fix the issues with the above mentioned certificate. And 1 month ago or so, I think there were even more countries issuing a certificate without a timezone (did not check again). 

Also, the current implementation already indicates that a missing timezone information shall be treated as UTC (note the null check for the 8th capturing group and addition of `Z`)

**Comment by dslmeinte** [comment]
Ah, I see that DCC is also already in this overview: https://github.com/eu-digital-green-certificates/dcc-quality-assurance/blob/main/SpecialCaseHandling.md

Are you, or another representative, present in the eHN Technical IOP Subgroup meeting on implementation issues?

**Comment by ubamrein** [comment]
Sadly, none of us are part of those meetings.

**Comment by dslmeinte** [comment]
I'm in it, so I'll try and make sure that it gets addressed. It's already in the overview, so that should help.

**Comment by dslmeinte** [comment]
It was already decided to that date-times without time zone offset should also be accepted (but maybe not encouraged), so this needs to happen. I invited you to the repo so that you can review the PR, if you like.
