### ISSUE TITLE
Clarify operand types

### ISSUE THREAD

**Issue by phmarek** [ehn-dcc-development/dgc-business-rules#4]
`main/certlogic/CertLogic-design.md` says:

> The following binary operators from JavaScript are available: ===, and, >, <, >=, <=, in, +. [...]  The operands must be comparable values: integers, strings, or datetimes.

Please clarify that the operands must have _identical_ types - "_compatible_" (in the JavaScript sense) is too weak, see the `'5' + 3` example from http://web.archive.org/web/20170721005756/http://blog.glaucus.in/wow-javascript-such-good-conventions-much-sense/.

**Comment by dslmeinte** [comment]
Good catch! The implementations already check for that, but I'll update the doc as well.

**Comment by dslmeinte** [comment]
Fixed here: https://github.com/ehn-digital-green-development/dgc-business-rules/blob/main/certlogic/certlogic-overall/documentation/specification.md

**Comment by phmarek** [comment]
Thanks!

> The operands must be comparable values: integers, or datetimes. All operands must be of the same type.

So strings (like eg. `2021-06-04T07:49:00+02:00`) are not comparable for less/bigger than? What about `==` comparisons?

**Comment by dslmeinte** [comment]
Correct: only integers and datetimes are deemed comparable. Datetimes can only be constructed through the `plusTime` (formerly: `plusDays`) operation.

`==` is also not part of CertLogic, but `===` is, and for al values, although I'm still thinking about limiting that a bit more.
