### ISSUE TITLE
Shouldn't we add the `or` operator?

### ISSUE THREAD

**Issue by ikbendewilliam** [ehn-dcc-development/dgc-business-rules#43]
Default jsonlogic supports `or` (https://jsonlogic.com/operations.html) but the `evaluator.ts` doesn't support this. Should we add this?
https://github.com/ehn-dcc-development/dgc-business-rules/blob/main/certlogic/certlogic-js/src/evaluator.ts

**Comment by dslmeinte** [comment]
We _could_ add it, but:

1. Does anyone have a concrete use case for it?
2. A workaround is: `P or Q = !( !P and !Q )` (De Morgan's laws). It visually blows up the expression a bit, obviously.

I'm hesitant to add operations/operators for developers' convenience: CertLogic is by design a simple, low-level format so that the specification can be tested effectively, and efficiently (in terms of person hours).

What's always possible is to “desugar” from a richer version of CertLogic to the actual CertLogic. The richer version can have an "or" which is compiled to `{ "not": [ { "and": [ { "not": [ <P> ] }, { "not": [ <Q> ] } ] } ] }`.

**Comment by ikbendewilliam** [comment]
I agree, I did use the workaround (for a specific case). I do agree that it isn't really required, but I wanted to ask, we've ported the typescript to Dart and I wanted to check now rather than having a bug later on where it became a requirement to be able to parse it.

**Comment by dslmeinte** [comment]
Can you share the Dart implementation? I'd like to have all implementations in the docs in the CertLogic repo.

But this perfectly demonstrates the point: adding things places a burden on all implementations, so I'd like to avoid adding things that are, ultimately, not really needed. There are other ways to help the developer experience (DX), like desugaring and custom/dedicated editors.

**Comment by ikbendewilliam** [comment]
I've created a PR with the code as a package (https://github.com/ehn-dcc-development/dgc-business-rules/pull/46)

**Comment by smithaaron** [comment]
> Does anyone have a concrete use case for it?

Yes. I'd like to validate data with an array of vaccinations. If any one of the vaccination records' `dn` matches the `sd` then the rule should be deemed to have passed.

I realise that DCCs only have one record, but this is for a different type of pass that can have multiple. Also, interestingly `dgca.verifier.app.decoder.model.GreenCertificate` defines Vaccine/Test/Recovery as lists.

Here's an example of what I'd like to use
`{
  "or": [
    {
      "if": [
        {
          "var": "payload.v.0"
        },
        {
          ">=": [
            {
              "var": "payload.v.0.dn"
            },
            {
              "var": "payload.v.0.sd"
            }
          ]
        },
        true
      ]
    },
    {
      "if": [
        {
          "var": "payload.v.1"
        },
        {
          ">=": [
            {
              "var": "payload.v.1.dn"
            },
            {
              "var": "payload.v.1.sd"
            }
          ]
        },
        true
      ]
    }
  ]
}`

**Comment by dslmeinte** [comment]
Hi @smithaaron ,
I see a couple of options here:

- “Emulate” an `or` by using De Morgan's Law: P or Q = !(!P and !Q) (generalises in an obvious way to “or”-ing more than 2 values). You can use the [_desugar CLI tool_](https://github.com/ehn-dcc-development/dgc-business-rules/blob/main/certlogic/certlogic-js/src/misc/desugar-cli.ts) for that: `certlogic-desugar`. (Documented [under here](https://github.com/ehn-dcc-development/dgc-business-rules/tree/main/certlogic/certlogic-js#commandline).)
- “Emulate” an `or` by chaining `if` operations: P or Q = if P then true else Q.
- Use `reduce` to iterate over `payload.v`, check the condition `dn >= sd` for each, and `or`-reduce those using De Morgan's Law.

I think option 3 is best for you. None of the options require adding an (`or`) operator.

**Comment by ikbendewilliam** [comment]
The easy way around this I use is using if [condition1, true, condition2]
```
{
  "if": [
    {
      "if": [
        {
          "var": "payload.v.0"
        },
        {
          ">=": [
            {
              "var": "payload.v.0.dn"
            },
            {
              "var": "payload.v.0.sd"
            }
          ]
        },
        true
      ]
    },
    true,
    {
      "if": [
        {
          "var": "payload.v.1"
        },
        {
          ">=": [
            {
              "var": "payload.v.1.dn"
            },
            {
              "var": "payload.v.1.sd"
            }
          ]
        },
        true
      ]
    }
  ]
}
```

**Comment by dslmeinte** [comment]
@ikbendewilliam 's solution is what I mean with option 2.
@smithaaron You have an idea how to do option 3?

**Comment by smithaaron** [comment]
Thank you both for your help.

@dslmeinte no, not yet. Will need to do more learning on that.

Btw, for option 2 (@ikbendewilliam's solution) it looks good for 2 records, but I guess if we're to have more elements in the array then this solution will become quite verbose, requiring even more nested ifs. Or am I missing something?

**Comment by dslmeinte** [comment]
@smithaaron option 3 should look something like
`
{
  "if": [
    {
      "var": "payload.v"
    },
    {
      "reduce": [
        {
          "var": "payload.v"
        },
        {
          "!": [
            {
              "and": [
                {
                  "!": [
                    {
                      "var": "accumulator"
                    }
                  ]
                },
                {
                  "!": [
                    {
                      ">=": [
                        {
                          "var": "current.dn"
                        },
                        {
                          "var": "current.sd"
                        }
                      ]
                    }
                  ]
                }
              ]
            }
          ]
        }
      ]
    },
    true
  ]
}
`

**Comment by smithaaron** [comment]
Thanks again. I can definitely work with that.
