### ISSUE TITLE
Complete documentation for Dart implementation

### ISSUE THREAD

**Issue by dslmeinte** [ehn-dcc-development/dgc-business-rules#48]
Specific points:

- [ ] Which version of the CertLogic specification is supported.
- [ ] How to install it (as a dependency).
- [ ] How to run the unit tests.

In any of these cases: minimal (e.g. referencing some standard knowledge from the Dart universe) is good enough.

**Comment by dslmeinte** [comment]
@ikbendewilliam Could you pick this up? I didn't want to make this part of the PR, but did want to check you can be assigned issues.

**Comment by ikbendewilliam** [comment]
Yes, I'll pick it up. I'm also fixing some issues (24 tests failed, and DateTime with short timezone wasn't supported)
