### ISSUE TITLE
Regular expression for data access path does not match text

### ISSUE THREAD

**Issue by ubamrein** [ehn-dcc-development/dgc-business-rules#5]
The text specifying valid paths for [variable access](https://github.com/ehn-dcc-development/dgc-business-rules/blob/main/certlogic/specification.md#data-access-var) says
> It must be composed of “path fragments” which are either “Lispy” words (starting with a word character followed by any number of word or number characters, or hyphens), or integers [...]

But the regular expression specified (`/^((\w[\w\d-]*)|\d+)(\.((\w[\w\d-]*)|\d+))*$/`) does not correspond exactly to the text as the `\w` character set means [any alpha-_numeric_ character including _](https://www.w3schools.com/jsref/jsref_regexp_wordchar.asp), which essentially means that the following regex would be identical: `^([\w-]+)(\.([\w-]+))*$`, hence the second capturing group will never be filled.

This can also be checked [here](https://regex101.com/) and e.g. extending the regex to use named capturing groups `^((?<Name>\w[\w\d-]*)|(?<Index>\d+))(\.((\w[\w\d-]*)|\d+))*$`.

**Comment by dslmeinte** [comment]
@ubamrein Sorry for the late reply. You're right: there is a mismatch.

The key point is that the path should be able to ”drill down” into a JSON data structure, with special meaning awarded to path fragments that happen to be non-negative integers. There's room for simplification here, which makes both the regex and spec simpler with less restrictions.

**Comment by dslmeinte** [comment]
How about the current formulation?: https://github.com/ehn-dcc-development/dgc-business-rules/tree/main/certlogic/specification#data-access-var

**Comment by ubamrein** [comment]
Sounds good :)
