### ISSUE TITLE
Datetime format typo?

### ISSUE THREAD

**Issue by lazka** [ehn-dcc-development/dgc-business-rules#63]
https://github.com/ehn-dcc-development/dgc-business-rules/blob/main/certlogic/specification/README.md#dates-and-date-times

It contains `YYYY-MM-DDThh:mm:ss.S+Z` which isn't valid ISO. Is this supposed to be `YYYY-MM-DDThh:mm:ss.SZ`?

Also all lines below that seem to contain one `+` too much?

**Comment by dslmeinte** [comment]
Thanks for noticing this.
Fixed this (quickly/without PR) with commit https://github.com/ehn-dcc-development/dgc-business-rules/commit/59ea9d822f46714535d57bf1a656656928d1bcc7

**Comment by lazka** [comment]
Thanks!
