### ISSUE TITLE
`dataAccesses` functionality for Kotlin

### ISSUE THREAD

**Issue by SchulzeStTSI** [ehn-dcc-development/dgc-business-rules#66]
The data accesses function in TypeScript would be also useful in kotlin. Can you please provide a implementation for that? :) 
I would also be very helpful when the function returns the used operator to the accessed field (e.g. "ci":["extractUVCI","===","<"], "mp":["==="]).

**Comment by dslmeinte** [comment]
Implemented with PR #68
