### ISSUE TITLE
plusTime does not evaluate data access in amount

### ISSUE THREAD

**Issue by M-Wong** [ehn-dcc-development/dgc-business-rules#7]
The `plusTime` operator does not evaluate data access values in the amount node. Additionally, in our tests, Jackson parsed the value 0 as a DoubleNode, causing the `evaluatePlusTime` method to throw an exception since it expected an IntNode for amount.

Consider adding support for evaluating data access in the `plusTime` amount as well as checking if the node is a numerical type instead of forcing it to be an IntNode:

```
internal fun evaluatePlusTime(dateOperand: JsonNode, amount: JsonNode, unit: JsonNode, data: JsonNode): JsonDateTime {
	var numericalNode = amount
	if (numericalNode is ObjectNode) {
		numericalNode = evaluate(amount, data)
	}

	val longAmount = if (numericalNode.isNumber) {
		numericalNode.longValue()
	} else {
		throw RuntimeException("\"amount\" argument (#2) of \"plusTime\" must be a number")
	}

	if (!isTimeUnit(unit)) {
		throw RuntimeException("\"unit\" argument (#3) of \"plusTime\" must be a string 'day' or 'hour'")
	}

	val timeUnit = TimeUnit.fromName(unit.textValue())
	val dateTimeStr = evaluate(dateOperand, data)
	if (dateTimeStr !is TextNode) {
		throw RuntimeException("date argument of \"plusTime\" must be a string")
	}
	return JsonDateTime.fromIso8601(dateTimeStr.asText()).plusTime(longAmount, timeUnit)
}
```

**Comment by dslmeinte** [comment]
OK, will look into the 0 as DoubleNode-problem right away.

As for making the `amount` operand a CL expression: what's the use case for this? Do you have to implement a concrete business rule that really requires that?

I'm happy to add things like that, but in the short term it's in our own interest to keep the language as small as we can get away with, so we can _test_ it as well as we can, and provide things like a sound type system as soon as possible.

**Comment by dslmeinte** [comment]
@M-Wong I have trouble reproducing the “0 as DoubleNode”-problem. Can you share a test/code that exposes it?

**Comment by M-Wong** [comment]
@dslmeinte Regarding the "0 as DoubleNode"-issue: Sorry to have raised this with you, turns out that was an issue on our side. We load our certlogic json from a server with additional information. Part of that is deserialized into data classes, while the logic is kept as a string, since it's anyway just passed down to Jackson and the certlogic class. However, our deserializer (Moshi) automatically converted integers to doubles even when kept as strings, hence Jackson would receive `0.0` instead of the original `0`. We managed to fix this by configuring Moshi differently.

Regarding the `amount` operator: We configure certain offsets and validity time ranges inside the value sets that we reference from the `plusTime` operator, since we also use those values in other places of the app. 
Example: 
```
"plusTime": [
  {
    "var": "payload.t.0.sc"
  },
  {
    "var": "external.valueSets.acceptance-criteria.rat-test-validity"
  },
  "hour"
]
```
The field `external.valueSets.acceptance-criteria.rat-test-validity` also comes from the server and is used for certlogic as well as other logic within the application. To make sure we use the same values everywhere, we used the `var` data access syntax in the `plusTime` operator.

**Comment by dslmeinte** [comment]
@M-Wong Regarding “0 as DoubleNode”: OK, thanks for clearing that up. I'll add a unit test to check whether Jackson has the expected behaviour nevertheless.

Regarding the evaluatable `amount` operand: the value sets are governed by an official EU body, so it's not possible to add value sets. Even if that were possible, it's not possible to add extra fields like this.

You could add additional external parameters (to the `external` object) to pass in extra data you think you need in your validation rules, but that's not regulated so would be an obstacle to other Member States being able to validate against your validation rules.

In this case, I would say: just put in the number of hours explicitly, as an integer value. Parametrizing rules like this anyway makes them less immutable than they're supposed to be. I'm assuming `rat-test-validity` is something like 72 hours?

**Comment by M-Wong** [comment]
@dslmeinte True, i guess our `acceptance-criteria` dictionary is misplaced in the `valueSets` property, it should be placed directly within external. Yes, `rat-test-validity` is 72 hours, and we also parametrized other validity values to reduce mistakes when reusing the same values. But I agree that this reduces the compatibility with other states and their validation rules. So in that case you can close this issue if an evaluatable `amount` is not desireable at this moment.

**Comment by dslmeinte** [comment]
Glad to find ourselves on the same page! Will close the issue.

Thanks for investing time in CertLogic! :)
