### ISSUE TITLE
TR-EU-0002 rule template

### ISSUE THREAD

**Issue by miguelzapaton** [ehn-dcc-development/dgc-business-rules#9]
Dear Meinte,

I'm really impressed how you invented certlogic in a question of days!!

I gave it a successful try with the new examples from the schema repo and stumbled over the following "typo":

In the template of the rule "TR-EU-0002" it seems that the condition has the wrong constant:

For RAT it must be "LP217198-3" and not "LP6464-4" which is NAAT.

-> https://github.com/ehn-dcc-development/ehn-dcc-schema/blob/release/1.3.0/valuesets/test-type.json

BTW: Are you planning to release an NPM packet for certlogic? It would make the integration a little bit easier.

Miguel

**Comment by dslmeinte** [comment]
Hi Miguel,

Thanks, but it mostly boils down to spec-ing languages often enough.

I am working to get things released as NPM packages: it would indeed make things easier.

You're right: I switched the IDs for RAT and NAAT around - I'll fix that in a minute.
