### ISSUE TITLE
Correct typo in documentation

### ISSUE THREAD

**Issue by kruzikh** [ehn-dcc-development/dgc-business-rules#95]
There is a typo in design-choices.md document, in the Operation: extract from UVCI:

"Also: the URN:**ICVI**: prefix is optional - e.g. UVCIs in DCCs issued by Luxembourg do not have the prefix."

**Should be:**

"Also: the URN:**UVCI**: prefix is optional - e.g. UVCIs in DCCs issued by Luxembourg do not have the prefix."

**Comment by dslmeinte** [comment]
Fixed here: https://github.com/ehn-dcc-development/dgc-business-rules/pull/96/files#diff-ba7b813dc2e9b6b1aa0bd5fe614e3fc73fab6d2909ee870ff6e10a310cced4e1R71

**Comment by dslmeinte** [comment]
Fixed in PR #96
